# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ruben-message-sender-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build **/MessageSenderApp.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish **/MessageSenderApp.sln -c Release -o ${{env.DOTNET_ROOT}}/MessageSenderApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: MessageSenderApp
          path: ${{env.DOTNET_ROOT}}/MessageSenderApp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Message Sender App Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: MessageSenderApp
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ruben-message-sender-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E016EE1B774942D784F97D0EA257DCB5 }}