# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy .Net Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build **/portfolio.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish **/portfolio.sln -c Release -o ${{env.DOTNET_ROOT}}/PortfolioWebApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: Portfolio-WebApp
          path: ${{env.DOTNET_ROOT}}/PortfolioWebApp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Portfolio Web App Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: Portfolio-WebApp
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ruben-portfolio'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8AD6F7B9F35041D4B9FE73521EB22C42 }}